#!/bin/sh
set -eu

check_minikube_install() {
    if [[ $(minikube 2>/dev/null)  =~ "minikube provisions and manages local Kubernetes" ]]; then
        return;
    fi
    echo "You must have minikube installed first"
    exit 0
}

check_minikube_running() {
    if [[ $(minikube status 2>/dev/null)  =~ "host: Running" ]]; then
        return;
    fi
    minikube start --listen-address=0.0.0.0
}

main() {
    if [[ $# -gt 0 ]]; then
        profile=$1
    else
        profile="1"
    fi
        if [[ $# -gt 1 ]]; then
        host=$2
        san="IP:$2"
    else
        host="localhost"
        san="DNS:localhost"
    fi
    if [[ $profile == "1" ]]; then
      app_port=8443
    fi
    if [[ $profile == "2" ]]; then
      app_port=8844
    fi
    if [[ $profile == "3" ]]; then
      app_port=8845
    fi
    if [[ $profile == "4" ]]; then
      app_port=8846
    fi
    check_minikube_install
    check_minikube_running
    minikube ssh "curl --silent https://raw.githubusercontent.com/l3murr/build_tools/refs/heads/main/dev-nginx.Dockerfile | docker build --build-arg SAN=$san --build-arg APP_URL=$host -t tms-nginx:v2 -"
    minikube ssh "curl --silent https://raw.githubusercontent.com/l3murr/build_tools/refs/heads/main/dev-server.Dockerfile | docker build -t tms-server:v2 -"
    minikube ssh "curl --silent https://raw.githubusercontent.com/l3murr/build_tools/refs/heads/main/dev-mysql.Dockerfile | docker build -t tms-mysql:v2 -"
    minikube ssh "curl --silent https://raw.githubusercontent.com/l3murr/build_tools/refs/heads/main/dev-websocket.Dockerfile | docker build -t tms-websocket:v2 -"
    curl --silent https://raw.githubusercontent.com/l3murr/build_tools/refs/heads/main/kube.dev.yaml | sed "s/\\$\\$/$profile/g" | sed "s/\\^\\^/$host/g" | sed "s/\\*\\*/$app_port/g" | minikube kubectl apply -- -f -
    
    keys=($(ls ~/.ssh))
    SSH_REGEX='^id_[a-zA-Z0-9]*'
    PK_REGEX='^id_[a-zA-Z0-9]*$'
    for i in "${keys[@]}"; do
        if [[ "$i" =~ $SSH_REGEX ]]; then
          minikube cp "$HOME/.ssh/$i" "minikube:/data/home/.ssh/$i"
        fi
        if [[ "$i" =~ $PK_REGEX ]]; then
          minikube ssh "sudo chmod 400 /data/home/.ssh/$i"
        fi
    done
    nginx=$(minikube kubectl get pods | grep -o 'nginx-[0-9a-z-]*')
    mysql=$(minikube kubectl get pods | grep -o "mysql-$profile-[0-9a-z-]*")
    if [[ $profile == "1" ]]; then
        minikube kubectl -- port-forward --address 0.0.0.0 "$nginx" 8083:8083 & \
        minikube kubectl -- port-forward --address 0.0.0.0 "$nginx" 5173:5173 & \
        minikube kubectl -- port-forward --address 0.0.0.0 "$nginx" 8443:8443 & \
        minikube kubectl -- port-forward --address 0.0.0.0 "$mysql" 3306:3306 & \
        echo "Press CTRL-C to stop port forwarding and exit the script"
        wait
        return
    fi
}

main "$@"
