kind: Deployment
apiVersion: apps/v1
metadata:
  name: nosql-$$
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nosql-$$
  template:
    metadata:
      labels:
        name: nosql-$$
    spec:
      containers:
        - image: amazon/dynamodb-local:2.6.1
          name: nosql-$$
          ports:
            - containerPort: 8000
              name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cache-$$
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cache-$$
  template:
    metadata:
      labels:
        name: cache-$$
    spec:
      containers:
        - image: memcached:1.6.38
          name: cache-$$
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 11211
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service-$$
spec:
  selector:
    name: cache-$$
  ports:
    - protocol: TCP
      port: 11211
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-$$
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-$$
  template:
    metadata:
      labels:
        name: mysql-$$
    spec:
      containers:
        - image: tms-mysql:v2
          name: mysql-$$
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /data/db_$$
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - image: tms-nginx:v2
          imagePullPolicy: Never
          name: nginx
          ports:
            - containerPort: 8443
              name: https-1
            - containerPort: 8444
              name: https-2
            - containerPort: 8445
              name: https-3
            - containerPort: 8446
              name: https-4
            - containerPort: 8083
              name: coder-1
            - containerPort: 8084
              name: coder-2
            - containerPort: 8085
              name: coder-3
            - containerPort: 8086
              name: coder-4
            - containerPort: 5173
              name: vite-1
            - containerPort: 5174
              name: vite-2
            - containerPort: 5175
              name: vite-3
            - containerPort: 5176
              name: vite-4
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-$$
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server-$$
  template:
    metadata:
      labels:
        name: server-$$
    spec:
      containers:
        - image: tms-server:v2
          imagePullPolicy: Never
          name: server-$$
          env:
            - name: APP_ENV
              value: "local"
            - name: DATABASE_URL
              value: "mysql://root:password@mysql-service-$$.default.svc.cluster.local/c45d86012a4e470091d7e186397a55a0"
            - name: CACHE_URL
              value: "memcache://cache-service-$$.default.svc.cluster.local:11211?verify_mode=none"
            - name: ENCRYPTION_KEY
              value: "testkey"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 8080
              name: coder
            - containerPort: 30000
              name: websocket
            - containerPort: 5173
              name: vite
          volumeMounts:
            - name: server-persistent-storage
              mountPath: /var/www/html
            - name: ssh
              mountPath: /root
          securityContext:
            privileged: true
      volumes:
        - name: server-persistent-storage
          hostPath:
            path: /data/code_$$
        - name: ssh
          hostPath:
            path: /data/home
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: websocket-$$
spec:
  replicas: 1
  selector:
    matchLabels:
      name: websocket-$$
  template:
    metadata:
      labels:
        name: websocket-$$
    spec:
      containers:
        - image: tms-websocket:v2
          name: websocket-$$
          ports:
            - containerPort: 8000
              name: websocket
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service-$$
spec:
  selector:
    name: websocket-$$
  ports:
    - protocol: TCP
      port: 8000
      name: websocket
---
apiVersion: v1
kind: Service
metadata:
  name: nosql-service-$$
spec:
  selector:
    name: nosql-$$
  ports:
    - protocol: TCP
      port: 8911
      name: nosql
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-$$
spec:
  selector:
    name: mysql-$$
  ports:
    - protocol: TCP
      port: 3306
      name: mysql
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: server-service-$$
spec:
  selector:
    name: server-$$
  ports:
    - protocol: TCP
      port: 8080
      name: coder
    - protocol: TCP
      port: 80
      name: app
    - protocol: TCP
      port: 30000
      name: websocket
    - protocol: TCP
      port: 5173
      name: vite
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  selector:
    name: nginx
  ports:
    - port: 8443
      name: app
    - port: 8083
      name: coder
    - port: 5173
      name: vite
  type: LoadBalancer
