kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-$$
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-$$
  template:
    metadata:
      labels:
        name: mysql-$$
    spec:
      containers:
        - image: mysql:8
          name: mysql-$$
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /data/code_$$
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - image: tms-nginx:v2
          imagePullPolicy: Never
          name: nginx
          ports:
            - containerPort: 443
              name: https-1
            - containerPort: 444
              name: https-2
            - containerPort: 445
              name: https-3
            - containerPort: 446
              name: https-4
            - containerPort: 8083
              name: coder-1
            - containerPort: 8084
              name: coder-2
            - containerPort: 8085
              name: coder-3
            - containerPort: 8086
              name: coder-4
            - containerPort: 5173
              name: vite-1
            - containerPort: 5174
              name: vite-2
            - containerPort: 5175
              name: vite-3
            - containerPort: 5176
              name: vite-4
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-$$
spec:
  replicas: 2
  selector:
    matchLabels:
      name: server-$$
  template:
    metadata:
      labels:
        name: server-$$
    spec:
      containers:
        - image: tms-server:v2
          imagePullPolicy: Never
          name: server-$$
          ports:
            - containerPort: 80
              name: http
            - containerPort: 8080
              name: coder
          volumeMounts:
            - name: server-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: server-persistent-storage
          hostPath:
            path: /data/db_$$
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: websocket-$$
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: centrifugo/centrifugo:v6
          name: websocket-$$
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 9000
              name: websocket
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: app-1
    - protocol: TCP
      port: 444
      targetPort: 444
      name: app-2
    - protocol: TCP
      port: 445
      targetPort: 445
      name: app-3
    - protocol: TCP
      port: 446
      targetPort: 446
      name: app-4
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: coder-1
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: coder-2
    - protocol: TCP
      port: 8085
      targetPort: 8085
      name: coder-3
    - protocol: TCP
      port: 8086
      targetPort: 8086
      name: coder-4
    - protocol: TCP
      port: 5173
      targetPort: 5173
      name: vite-1
    - protocol: TCP
      port: 5174
      targetPort: 5174
      name: vite-2
    - protocol: TCP
      port: 5175
      targetPort: 5175
      name: vite-3
    - protocol: TCP
      port: 5176
      targetPort: 5176
      name: vite-4
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service-$$
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: websocket-$$
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: websocket
---
apiVersion: v1
kind: Service
metadata:
  name: server-service-$$
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: server-$$
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: coder
    - protocol: TCP
      port: 80
      targetPort: 89
      name: app
    - protocol: TCP
      port: 5173
      targetPort: 5173
      name: vite
